apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  namespace: default
spec:
  nodeName: k3s1
  containers:
  - name: busybox1
    image: busybox:1.28
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always