CERTMANAGER_VERSION=v1.7.1
ADMINPASSWORD=Test#2022
LONGHORNUIUSER=longhorn; 
LONGHORNUIPASSWORD=$ADMINPASSWORD;
DATAPATH="/Users/scorbarieu/longhorn"
#ADMINUSER=vagrant #requires sudo
CLUSTERADMINUSER=scorbarieu
CLUSTERMASTER=localhost