- name: Update all Debian family packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install open-iscsi
  ansible.builtin.apt:
    name: open-iscsi
    state: present
  notify:
  - Enable iscsid
  - Load iscsi_tcp

- name: Install nfs-common
  ansible.builtin.apt:
    name: nfs-common
    state: present